apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    IO stress on a app pods belonging to an app deployment
kind: ChaosExperiment
metadata:
  name: demo-hub-chart-pod-io-stress-nginx-level-1
  labels:
    name: demo-hub-chart-pod-io-stress-nginx-level-1
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - batch
          - apps
          - apps.openshift.io
          - argoproj.io
          - litmuschaos.io
        resources:
          - jobs
          - pods
          - pods/log
          - replicationcontrollers
          - deployments
          - statefulsets
          - daemonsets
          - replicasets
          - deploymentconfigs
          - rollouts
          - pods/exec
          - events
          - chaosengines
          - chaosexperiments
          - chaosresults
        verbs:
          - create
          - list
          - get
          - patch
          - update
          - delete
          - deletecollection
    image: litmuschaos/go-runner:ci
    imagePullPolicy: Always
    args:
      - -c
      - ./experiments -name pod-io-stress
    command:
      - /bin/bash
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "120"
      - name: FILESYSTEM_UTILIZATION_PERCENTAGE
        value: "10"
      - name: FILESYSTEM_UTILIZATION_BYTES
        value: ""
      - name: NUMBER_OF_WORKERS
        value: "4"
      - name: PODS_AFFECTED_PERC
        value: ""
      - name: VOLUME_MOUNT_PATH
        value: ""
      - name: TARGET_PODS
        value: ""
      - name: RAMP_TIME
        value: ""
      - name: LIB
        value: "pumba"
      - name: LIB_IMAGE
        value: "litmuschaos/go-runner:ci"
      - name: CONTAINER_RUNTIME
        value: "docker"
      - name: SOCKET_PATH
        value: "/var/vcap/sys/run/docker/docker.sock"
      - name: SEQUENCE
        value: "parallel"
    labels:
      name: demo-hub-chart-pod-io-stress-nginx-level-1
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
